### ISSUE TITLE
Broken Burger Menu

### ISSUE THREAD

**Issue by cpraschl** [CamTrap2024/camtrap2024.github.io#3]
Probably due to the size ratio of the logo, the burger menu is broken.

![image](https://github.com/CamTrap2024/camtrap2024.github.io/assets/38362068/4f92be59-8107-4f6c-ac97-5871711428ad)

**Comment by cpraschl** [comment]
![image](https://github.com/CamTrap2024/camtrap2024.github.io/assets/38362068/a01dbc12-0846-47ed-9fd3-d1971ff92d8f)


margin: 0px for the `<a>` element should improve it.

**Comment by schedldave** [comment]
min-height is set and font is also smaller now. 
I would not make more changes here. :)
